### PR TITLE
Enable compilation for more constrained environments

### PR DESCRIPTION
**Pull request by martindisch**
- Throw out bzip2 feature of zip crate (requires libbz2)
- Add feature to disable rayon (requires threads)

### CODE REVIEW

**Comment by zacharywhitley** [comment]
Just wanted to put in a +1 for getting this merged. I finally finished the project that prompted me to submit the "Add WASM support" issue and I'd love to make Lingua the first wasm function I add! The project was adding support for writing user defined functions for a database in wasm so you could run it from anywhere rather than having to install them. With lingua you'd be able to write "SELECT wasm_call("http://path/to/lingua-wasm", myText) FROM MyTable" and get the inferred language. I'm hoping to port it to multiple databases so that you can call the same function from any platform. mysql, postgres, ksql, etc.

**Comment by martindisch** [comment]
That's a neat idea! I think Wasm and Rust are really going to shine when it comes to implementing plugin functionality in all kinds of software, I've been seeing lots of similar examples recently. Very exciting space!

I was happy to see that in the meantime Peter has reworked the functionality in a way that makes more sense, with an opt-in feature for rayon/parallelism. So it looks pretty much ready.

**Comment by pemistahl** [comment]
Hi @zacharywhitley and @martindisch, I will continue to work on this. I was busy doing other things recently, including a Covid-19 infection. :( Please be patient.

**Comment by zacharywhitley** [comment]
I'm really sorry to hear that. I hope it wasn't too bad and you're doing well and recovering. No hurries. I only added the comment because you seemed to appreciate people using your library. Just an additional detail about how I'm using it. It's for a graph database called Stardog that supports RDF. If you're not familiar RDF it includes support for language tags for text literals. Unfortunately most text doesn't include language tags which is where Lingua comes to the rescue. I've already written a plugin using the Java version. thank you very much. and I'm now transitioning over to a WebAssembly based plugin system.

Something just occurred to me after reading another recent post you responded to. I could probably write a plugin that will train a custom model based on literals in the database that are tagged too tag literals that aren't tagged. How cool would that be?

**Comment by zacharywhitley** [comment]
@martindisch don't leave me hanging., what is it?

**Comment by martindisch** [comment]
Haha, sorry about that :) The library loads language models out of zipped JSON either at startup or lazily on demand. When trying to use it in a Wasm context where you end up destroying and recreating the environment every time you detect the language, that's rather costly. I'm seeing if I can reduce the startup penalty by using [rkyv](https://rkyv.org/zero-copy-deserialization.html) to directly compile the language models into the binary in a representation that can be memory-mapped at no cost at runtime. The problem is that this trades computation for binary size, which balloons heavily. So it may be useful for isolated use cases, but very likely not as a default since the startup cost is negligible in normal usage anyway.

**Comment by pemistahl** [comment]
I merge this PR now and continue working in the main branch. We can open a new [discussion](https://github.com/pemistahl/lingua-rs/discussions) if you like.

**Comment by martindisch** [comment]
That's wonderful, thank you!

**Pull request merged**
